spring:
        datasource:
                url: jdbc:mysql://localhost:3306/jpa_tp?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
                username: root
                driver-class-name: com.mysql.cj.jdbc.Driver
server:
        port: 7777